name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: Build XPI
      run: npx zp-zipup src batch-obsidian-export .gitkeep
    - name: Upload XPI as Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: xpi/*.xpi
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
